FROM node:18-alpine

WORKDIR /app

# Install dependencies
COPY packages/shared-library/package*.json ./
RUN npm install

# Copy source code
COPY packages/shared-library .

EXPOSE 8084

CMD ["npm", "run", "dev"]