FROM node:18-alpine

# Copy scripts to parent directory (won't be overridden by volume mount)
COPY scripts /scripts

WORKDIR /app

# Install dependencies
COPY packages/shell-app/package*.json ./
RUN npm install

# Copy source code
COPY packages/shell-app .

EXPOSE 9000

CMD ["npm", "start"]