FROM node:18-alpine

# Copy scripts to parent directory (won't be overridden by volume mount)
COPY scripts /scripts

WORKDIR /app

# Install dependencies
COPY packages/react-mfe/package*.json ./
RUN npm install

# Copy source code
COPY packages/react-mfe .

EXPOSE 8081

CMD ["npm", "start"]